
FROM	oven/bun:latest	AS	build
WORKDIR	/app
COPY	package.json	./
COPY	bun.lockb	./
RUN	bun install
COPY	.	.
RUN	bunx --bun vite build
FROM	nginx:alpine
COPY	/app/dist	/usr/share/nginx/html
COPY	nginx.conf	/etc/nginx/conf.d/default.conf
EXPOSE	80
CMD	["nginx","-g","daemon off;"]
